package com.anyproto.anyfile.data.crypto

import org.bouncycastle.crypto.Signer
import org.bouncycastle.crypto.params.Ed25519PrivateKeyParameters
import org.bouncycastle.crypto.params.Ed25519PublicKeyParameters
import org.bouncycastle.crypto.signers.Ed25519Signer
import org.bouncycastle.util.Arrays
import java.security.KeyFactory
import java.security.PrivateKey
import java.security.PublicKey
import java.security.Signature
import java.security.spec.PKCS8EncodedKeySpec
import java.security.spec.X509EncodedKeySpec

/**
 * Pure Kotlin Ed25519 implementation using Bouncy Castle's low-level API.
 *
 * This implementation bypasses Android's JCA KeyFactory limitation by using
 * Bouncy Castle's Ed25519Signer directly for signing and verification.
 *
 * For key loading from PKCS#8/X.509 format (needed for TLS), we use a workaround:
 * - Extract raw 32-byte keys from PKCS#8/X.509 format
 * - Use Bouncy Castle's Ed25519PublicKeyParameters and Ed25519PrivateKeyParameters
 *
 * Based on:
 * - Bouncy Castle Ed25519Signer API
 * - RFC 8032: EdDSA for Curves25519 and Ed448
 */
object PureEd25519 {

    private const val PRIVATE_KEY_SEED_SIZE = 32
    private const val PUBLIC_KEY_SIZE = 32
    private const val SIGNATURE_SIZE = 64

    // PKCS#8 encoded Ed25519 private key is 48 bytes (12-byte header + 32-byte seed + 4-byte footer)
    private const val PKCS8_PRIVATE_KEY_SIZE = 48

    // X.509 encoded Ed25519 public key is 44 bytes (12-byte header + 32-byte key)
    private const val X509_PUBLIC_KEY_SIZE = 44

    /**
     * Generate a new Ed25519 key pair.
     *
     * Uses Bouncy Castle's Ed25519 key generation.
     *
     * @return Pair of (privateKey, publicKey) as Ed25519PrivateKeyParameters and Ed25519PublicKeyParameters
     */
    fun generateKeyPair(): Pair<Ed25519PrivateKeyParameters, Ed25519PublicKeyParameters> {
        // Generate a random 32-byte seed
        val seed = ByteArray(PRIVATE_KEY_SEED_SIZE)
        java.security.SecureRandom().nextBytes(seed)

        // Bouncy Castle Ed25519PrivateKeyParameters takes the seed as byte array
        val privateKey = Ed25519PrivateKeyParameters(seed)

        // Generate public key by encoding the private key
        // Ed25519 private key encodes to 64 bytes (32 seed + 32 public key)
        val privateKeyEncoded = privateKey.encoded
        val publicKeyBytes = ByteArray(PUBLIC_KEY_SIZE)
        System.arraycopy(privateKeyEncoded, 32, publicKeyBytes, 0, PUBLIC_KEY_SIZE)

        // Create public key parameters from the derived public key bytes
        val publicKey = Ed25519PublicKeyParameters(publicKeyBytes)

        return Pair(privateKey, publicKey)
    }

    /**
     * Generate a new Ed25519 key pair in PKCS#8/X.509 format.
     *
     * Returns keys in the standard encoded format for use with Android's KeyFactory
     * and TLS certificates.
     *
     * @return Libp2pKeyPair containing PKCS#8 private key and X.509 public key
     */
    fun generateKeyPairEncoded(): com.anyproto.anyfile.data.network.libp2p.Libp2pKeyPair {
        val keyPairGenerator = java.security.KeyPairGenerator.getInstance(
            "Ed25519",
            org.bouncycastle.jce.provider.BouncyCastleProvider.PROVIDER_NAME
        )
        val keyPair = keyPairGenerator.generateKeyPair()

        val privateKeyEncoded = keyPair.private.encoded
        val publicKeyEncoded = keyPair.public.encoded

        return com.anyproto.anyfile.data.network.libp2p.Libp2pKeyPair(
            privateKey = privateKeyEncoded,
            publicKey = publicKeyEncoded
        )
    }

    /**
     * Generate a new Ed25519 key pair as raw byte arrays.
     *
     * Uses Bouncy Castle's Ed25519 key generation and returns raw 32-byte keys.
     * This version works consistently on both JVM (unit tests) and Android runtime.
     *
     * @return Libp2pKeyPair containing raw 32-byte private key seed and 32-byte public key
     */
    fun generateKeyPairRaw(): com.anyproto.anyfile.data.network.libp2p.Libp2pKeyPair {
        // Generate a random 32-byte seed
        val seed = ByteArray(PRIVATE_KEY_SEED_SIZE)
        java.security.SecureRandom().nextBytes(seed)

        // Bouncy Castle Ed25519PrivateKeyParameters takes the seed as byte array
        val privateKeyParams = Ed25519PrivateKeyParameters(seed)

        // Derive public key from private key
        // The public key is generated by computing public = H(seed) * B
        // We can get the encoded public key bytes directly from Ed25519PublicKeyParameters
        val publicKeyParams = privateKeyParams.generatePublicKey()

        // Return raw 32-byte keys
        return com.anyproto.anyfile.data.network.libp2p.Libp2pKeyPair(
            privateKey = seed,  // 32-byte seed
            publicKey = publicKeyParams.encoded  // 32-byte public key
        )
    }

    /**
     * Sign a message with an Ed25519 private key.
     *
     * Uses Bouncy Castle's Ed25519Signer for signing.
     *
     * @param privateKey Ed25519PrivateKeyParameters
     * @param message Message to sign
     * @return 64-byte Ed25519 signature
     */
    fun sign(privateKey: Ed25519PrivateKeyParameters, message: ByteArray): ByteArray {
        val signer: Signer = Ed25519Signer()
        signer.init(true, privateKey)
        signer.update(message, 0, message.size)
        return signer.generateSignature()
    }

    /**
     * Verify an Ed25519 signature.
     *
     * Uses Bouncy Castle's Ed25519Signer for verification.
     *
     * @param publicKey Ed25519PublicKeyParameters
     * @param message Message that was signed
     * @param signature 64-byte Ed25519 signature
     * @return true if signature is valid
     */
    fun verify(publicKey: Ed25519PublicKeyParameters, message: ByteArray, signature: ByteArray): Boolean {
        val signer: Signer = Ed25519Signer()
        signer.init(false, publicKey)
        signer.update(message, 0, message.size)
        return signer.verifySignature(signature)
    }

    /**
     * Sign a message with an Ed25519 private key in PKCS#8 format.
     *
     * This version extracts the raw 32-byte seed from PKCS#8 and uses
     * Bouncy Castle's Ed25519Signer for signing.
     *
     * @param privateKey PKCS#8 encoded Ed25519 private key (48 bytes)
     * @param message Message to sign
     * @return 64-byte Ed25519 signature
     */
    fun signPkcs8(privateKey: ByteArray, message: ByteArray): ByteArray {
        require(privateKey.size == PKCS8_PRIVATE_KEY_SIZE) {
            "Private key must be $PKCS8_PRIVATE_KEY_SIZE bytes, got ${privateKey.size}"
        }

        // Extract raw 32-byte seed from PKCS#8
        val rawSeed = extractRawPrivateKey(privateKey)

        // Create Ed25519PrivateKeyParameters from the seed
        val privateKeyParams = Ed25519PrivateKeyParameters(rawSeed)

        return sign(privateKeyParams, message)
    }

    /**
     * Verify an Ed25519 signature with a public key in X.509 format.
     *
     * This version extracts the raw 32-byte public key from X.509 and uses
     * Bouncy Castle's Ed25519Signer for verification.
     *
     * @param publicKey X.509 encoded Ed25519 public key (44 bytes)
     * @param message Message that was signed
     * @param signature 64-byte Ed25519 signature
     * @return true if signature is valid, false otherwise
     */
    fun verifyX509(publicKey: ByteArray, message: ByteArray, signature: ByteArray): Boolean {
        require(publicKey.size >= X509_PUBLIC_KEY_SIZE) {
            "Public key must be at least $X509_PUBLIC_KEY_SIZE bytes, got ${publicKey.size}"
        }
        require(signature.size == SIGNATURE_SIZE) {
            "Signature must be $SIGNATURE_SIZE bytes, got ${signature.size}"
        }

        // Extract raw 32-byte public key from X.509
        val rawPublicKey = extractRawPublicKey(publicKey)

        // Create Ed25519PublicKeyParameters from the raw key
        val publicKeyParams = Ed25519PublicKeyParameters(rawPublicKey)

        return verify(publicKeyParams, message, signature)
    }

    /**
     * Extract the raw 32-byte public key from X.509 encoded format.
     *
     * X.509 format for Ed25519: 12-byte ASN.1 header + 32-byte key + trailing data
     * The public key bytes start after the ASN.1 header.
     *
     * @param x509PublicKey X.509 encoded Ed25519 public key (44 bytes)
     * @return Raw 32-byte public key
     */
    fun extractRawPublicKey(x509PublicKey: ByteArray): ByteArray {
        require(x509PublicKey.size >= X509_PUBLIC_KEY_SIZE) {
            "X.509 public key must be at least $X509_PUBLIC_KEY_SIZE bytes, got ${x509PublicKey.size}"
        }

        // X.509 structure for Ed25519:
        // 0x30 0x2A 0x30 0x05 0x06 0x03 0x2B 0x65 0x70 0x03 0x21 0x00 [32-byte key]
        // The key starts at offset 12
        val rawKey = ByteArray(PUBLIC_KEY_SIZE)
        System.arraycopy(x509PublicKey, 12, rawKey, 0, PUBLIC_KEY_SIZE)
        return rawKey
    }

    /**
     * Extract the raw 32-byte private key seed from PKCS#8 encoded format.
     *
     * PKCS#8 format for Ed25519: header + 32-byte seed + footer
     * The private seed is embedded in the PKCS#8 structure.
     *
     * @param pkcs8PrivateKey PKCS#8 encoded Ed25519 private key (48 bytes)
     * @return Raw 32-byte private key seed
     */
    fun extractRawPrivateKey(pkcs8PrivateKey: ByteArray): ByteArray {
        require(pkcs8PrivateKey.size >= PKCS8_PRIVATE_KEY_SIZE) {
            "PKCS#8 private key must be at least $PKCS8_PRIVATE_KEY_SIZE bytes, got ${pkcs8PrivateKey.size}"
        }

        // PKCS#8 structure for Ed25519:
        // 0x30 0x2E 0x02 0x01 0x00 0x30 0x05 0x06 0x03 0x2B 0x65 0x70
        // 0x04 0x20 0x04 0x14 [32-byte seed] 0xA1 0x01 0x01
        // The seed starts at offset 16
        val rawKey = ByteArray(PRIVATE_KEY_SEED_SIZE)
        System.arraycopy(pkcs8PrivateKey, 16, rawKey, 0, PRIVATE_KEY_SEED_SIZE)
        return rawKey
    }

    /**
     * Create Ed25519PrivateKeyParameters from PKCS#8 encoded key.
     *
     * @param pkcs8PrivateKey PKCS#8 encoded Ed25519 private key (48 bytes)
     * @return Ed25519PrivateKeyParameters
     */
    fun privateKeyFromPkcs8(pkcs8PrivateKey: ByteArray): Ed25519PrivateKeyParameters {
        val rawSeed = extractRawPrivateKey(pkcs8PrivateKey)
        return Ed25519PrivateKeyParameters(rawSeed)
    }

    /**
     * Create Ed25519PublicKeyParameters from X.509 encoded key.
     *
     * @param x509PublicKey X.509 encoded Ed25519 public key (44 bytes)
     * @return Ed25519PublicKeyParameters
     */
    fun publicKeyFromX509(x509PublicKey: ByteArray): Ed25519PublicKeyParameters {
        val rawKey = extractRawPublicKey(x509PublicKey)
        return Ed25519PublicKeyParameters(rawKey)
    }
}

/**
 * Exception thrown when pure Ed25519 operations fail.
 */
class PureEd25519Exception(message: String, cause: Throwable? = null) : Exception(message, cause)
